version: '3.3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'challengedb'
      MYSQL_USER: 'challengeuser'
      MYSQL_PASSWORD: 'challengepassword'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
volumes:
  my-db: